FROM nodered/node-red:latest

# Install additional npm packages
RUN npm install --unsafe-perm --no-update-notifier --no-fund --only=production  binary-parser node-red-contrib-uuid
    
COPY flow.json /data/flows.json

# expose UDP port 33740 and 33739 for GT7
EXPOSE 33740/udp
EXPOSE 33739/udp
